run:
  timeout: 5m
  go: "1.21"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - dupl
    - durationcheck
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tenv
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace

linters-settings:
  errcheck:
    # Ignore fluent API methods that return receivers for chaining
    exclude-functions:
      - fmt.Print
      - fmt.Printf
      - fmt.Println
    ignore-type-assertions: true
  
  funlen:
    lines: 100
    statements: 50
  
  cyclop:
    max-complexity: 15
  
  lll:
    line-length: 120
  
  gomnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - hugeParam

issues:
  exclude:
    # Ignore fluent API methods - these return receivers for chaining, not errors to check
    - "Error return value of `.*\\.With.*` is not checked"
    - "Error return value of `.*\\.Add.*` is not checked"
    - "Error return value of `.*\\.Clear.*` is not checked" 
    - "Error return value of `.*\\.Filter.*` is not checked"
    - "Error return value of `collection\\..*` is not checked"
    - "Error return value of `.*\\.Error\\(\\)` is not checked"
    # Allow context keys as strings in tests and examples  
    - "should not use basic type.*as key in context.WithValue"
    # Allow unused parameters in test functions
    - "parameter.*seems to be unused.*consider removing"
    # Allow global variables for configuration
    - "globalStructuredLogger is a global variable"
    - "globalConfig is a global variable"
    - "globalConfigMu is a global variable"
    # Allow package comments to be flexible
    - "should have a package comment"
    - "comment on exported.*should be of the form"
    # Allow context fields in builder structs
    - "found a struct that contains a context.Context field"
    # Allow ALL_CAPS for constants (vAI standard)
    - "don't use ALL_CAPS in Go names"
    # Allow repeated strings in tests
    - "has .* occurrences, make it a constant"
    # Allow builtin redefinition in limited scope
    - "redefinition of the built-in function"
  
  exclude-rules:
    # Exclude magic number checks for HTTP status codes
    - path: cuserr\.constants\.errors\.go
      linters:
        - gomnd
    
    # Exclude magic number checks for test files  
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - gocognit
        - dupl
        - cyclop
        - errcheck
        - gosec
        - testpackage
    
    # Exclude strict linting for examples  
    - path: examples/
      linters:
        - errcheck
        - forbidigo
        - unused
        - gosec
    
    # Exclude some linters for examples
    - path: examples/
      linters:
        - gochecknoglobals
        - gochecknoinits
        - funlen
        - gomnd
        - lll

  exclude-use-default: false

severity:
  default-severity: error